sudo: false

language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "pypy"
install:
    - pip install pipenv
    - pipenv sync -d
script:
    - pipenv run make lint
    - pipenv run py.test
    - pipenv run make doc

notifications:
  irc:
    channels:
    - "chat.freenode.net#python-effect"
    skip_join: true
    use_notice: true
    template:
      - "%{repository} %{branch} %{commit} by %{author}: %{message}  %{build_url}"
