language: python
python:
    - "2.7"
    - "2.6"
    - "3.4"
    - "pypy"
install:
    - pip install -r dev-requirements.txt --use-mirrors
script:
    - make lint
    - trial effect
    - trial examples

