language: python
python:
    - "2.7"
    - "2.6"
    - "3.4"
    - "pypy"
install:
    - pip install -r dev-requirements.txt
    - pip install six
    - pip install discover
    - pip install 'characteristic>=14.0.0'
    - pip install sphinx
script:
    - make lint
    - python -mtesttools.run discover --list
    - python -mtesttools.run discover
    - make doc

notifications:
  irc:
    channels:
    - "chat.freenode.net#python-effect"
    skip_join: true
    use_notice: true
